# Generated by Django 2.1.8 on 2019-04-16 08:08

from django.db import migrations, models
import ecommerce.products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=ecommerce.products.models.upload_image_path),
        ),
    ]
