# Generated by Django 2.1.8 on 2019-04-16 09:02

from django.db import migrations, models
import ecommerce.products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=ecommerce.products.models.upload_image_path),
        ),
    ]
